### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by My12123** [Atharva-Phatak/Manga-Colorizer#15]
(venv) F:\Manga-Colorizer\src>python F:\Manga-Colorizer\src\train-gan.py
Traceback (most recent call last):
  File "F:\Manga-Colorizer\src\train-gan.py", line 28, in <module>
    train_dl = torch.utils.data.DataLoader(train_ds, batch_size=16, shuffle=True)
  File "F:\Manga-Colorizer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 349, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "F:\Manga-Colorizer\venv\lib\site-packages\torch\utils\data\sampler.py", line 140, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by Keiser04** [comment]
that happened to me with manga colorizer, you are missing the examples for the test (equivalent to real_manga).
